//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lecturer
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(40, 85, ErrorMessage = "Lecturer should between 40 - 85 years")]
        public Nullable<int> Age { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Material { get; set; }
        [Required]
        public Nullable<int> UnvId { get; set; }
        [Required]
        [RegularExpression(@"\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b", ErrorMessage = "invalid email format")]
        public string Email { get; set; }
        [Required]
        [StringLength(12, MinimumLength = 6, ErrorMessage = "Password shoud be between 6 - 12 charactor")]
        public string Password { get; set; }
        
        public virtual University University { get; set; }
    }
}
