//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(19, 30, ErrorMessage = "Student should between 19 - 30 years")]
        public Nullable<int> Age { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Collage { get; set; }
        [Required]
        [Range(55, 99, ErrorMessage = "Average should between 55 - 99")]
        public Nullable<double> Average { get; set; }
        [Required]
        public Nullable<int> UnvId { get; set; }
        
        public virtual University University { get; set; }
    }
}
